# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: all
    commit-message:
      prefix: "npm Updates: "
    versioning-strategy: lockfile-only
    groups:
      all-dependencies:
        patterns:
          - "*"
